version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci

  run-tests:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Run Vitest tests
          command: |
            npx vitest run --reporter=dot

workflows:
  version: 2
  test:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
