version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            npm install -D vitest

  run-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Vitest tests
          command: |
            npm run test

workflows:
  version: 2
  test:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
